name = "valguard"
version = "0.2.0"
description = "A Gleam validation library for form and api endpoint validation"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ross-byrne", repo = "valguard" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
